// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLb4DnJT1LNfFqp4sj-WxuM6AMPLcFN3E',
    appId: '1:429712783527:web:17e7cc3cf0aa5a764fc382',
    messagingSenderId: '429712783527',
    projectId: 'medivault-e4dac',
    authDomain: 'medivault-e4dac.firebaseapp.com',
    storageBucket: 'medivault-e4dac.firebasestorage.app',
    measurementId: 'G-ESCRXNLC3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0qlRsYyaY1vDTHkbjOAxwX6iKm8CPGGI',
    appId: '1:429712783527:android:cb5d6708bcc8955f4fc382',
    messagingSenderId: '429712783527',
    projectId: 'medivault-e4dac',
    storageBucket: 'medivault-e4dac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRD7J-W1515JMJ8lej61sTyGkk1Kydrp8',
    appId: '1:429712783527:ios:c8ab7de5d8313bdf4fc382',
    messagingSenderId: '429712783527',
    projectId: 'medivault-e4dac',
    storageBucket: 'medivault-e4dac.firebasestorage.app',
    iosBundleId: 'com.example.medivault',
  );
}
